# Generated by Django 5.2.6 on 2025-10-31 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_texte', models.CharField(blank=True, help_text='Ex: 2 heures, demi-journée...', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_cuisine', models.CharField(max_length=50)),
                ('prix_moyen_eur', models.FloatField(default=0.0, help_text='Coût moyen estimé par personne (à titre indicatif).')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('description_generale', models.TextField(blank=True, null=True)),
                ('image_banniere', models.ImageField(blank=True, null=True, upload_to='img_villes/')),
            ],
            options={
                'verbose_name_plural': 'Villes (Destinations)',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('resume_inspirant', models.TextField(blank=True, max_length=500, null=True)),
                ('duree_standard_jours', models.PositiveSmallIntegerField(choices=[(1, '1 jour'), (3, '3 jours'), (5, '5 jours'), (8, '8 jours'), (10, '10 jours')], default=3)),
                ('prix_par_personne_euros', models.FloatField(default=0.0, help_text='Prix par personne pour la durée standard du pack.')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('activites', models.ManyToManyField(help_text='Liste des activités incluses dans ce pack.', related_name='packs', to='Appli.activite')),
                ('restaurants', models.ManyToManyField(blank=True, help_text='Liste des restaurants visités ou recommandés.', related_name='packs', to='Appli.restaurant')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='Appli.ville')),
            ],
            options={
                'ordering': ['ville', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('demande', 'Demande effectuée'), ('en cours', 'En cours de traitement'), ('annulé', 'Demande Annulée'), ('traitée', 'Demande traitée'), ('validée', 'Transaction effectuée')], default='demande', max_length=60)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('nb_personne', models.SmallIntegerField()),
                ('montant_total', models.FloatField(default=0.0)),
                ('devise_paiement', models.CharField(blank=True, choices=[('EUR', '€ (Euros)'), ('MAD', 'DH (Dirhams Marocains)'), ('DOLLAR', '$ (Dollars)')], max_length=20, null=True)),
                ('type_virement', models.CharField(blank=True, max_length=60, null=True)),
                ('lien_de_paiement', models.URLField(blank=True, max_length=300, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appli.pack')),
                ('traiter_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_traites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_demande'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='Appli.ville'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_activite', to='Appli.activite')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Appli.pack')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_ville', to='Appli.ville')),
            ],
        ),
        migrations.AddField(
            model_name='activite',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='Appli.ville'),
        ),
        migrations.CreateModel(
            name='DescriptionJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_jour', models.PositiveSmallIntegerField()),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='Appli.pack')),
            ],
            options={
                'ordering': ['numero_jour'],
                'unique_together': {('pack', 'numero_jour')},
            },
        ),
    ]
