# Generated by Django 5.2.6 on 2025-11-02 15:03

import Appli.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_activites_jour/')),
            ],
        ),
        migrations.CreateModel(
            name='PackComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_pack', models.CharField(choices=[('AVENTURE', 'Aventure & Exploration'), ('LUXE', 'Séjour Luxe & Exclusif'), ('IMMERSION', 'Immersion Culturelle & Tradition'), ('DETENTE', 'Détente & Bien-être'), ('SUR_MESURE', 'Pack Sur Mesure')], default='SUR_MESURE', max_length=20)),
                ('duree_jours', models.PositiveIntegerField(default=3)),
                ('duree_nuits', models.PositiveIntegerField(default=2)),
                ('prix_mad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_packs_complet/')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_villes/')),
            ],
        ),
        migrations.CreateModel(
            name='PackJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_packs_jour/')),
                ('activites', models.ManyToManyField(related_name='packs_jour', to='Appli.activitejour')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPackComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_personne', models.PositiveIntegerField(default=1)),
                ('devise', models.CharField(choices=[('MAD', 'Dirham marocain'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='MAD', max_length=10)),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
                ('date_fin', models.DateField(default=Appli.models.default_end_date)),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('demande', 'Demande effectuée'), ('en cours', 'En cours de traitement'), ('annulé', 'Annulée'), ('traitée', 'Traitée'), ('validée', 'Validée')], default='demande', max_length=20)),
                ('pack', models.ForeignKey(default=Appli.models.default_pack_complet, on_delete=django.db.models.deletion.CASCADE, to='Appli.packcomplet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationPackJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_personne', models.PositiveIntegerField(default=1)),
                ('devise', models.CharField(choices=[('MAD', 'Dirham marocain'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='MAD', max_length=10)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('pack', models.ForeignKey(default=Appli.models.default_pack_jour, on_delete=django.db.models.deletion.CASCADE, to='Appli.packjour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_option', models.CharField(max_length=100)),
                ('type_option', models.CharField(blank=True, choices=[('GASTRONOMIQUE', 'Gastronomique'), ('TRADITIONNEL', 'Cuisine Marocaine'), ('FUSION', 'Fusion / Moderne'), ('VEGETARIEN', 'Végétarien')], max_length=50, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('reservation_complet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Appli.reservationpackcomplet')),
                ('reservation_jour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Appli.reservationpackjour')),
            ],
        ),
        migrations.AddField(
            model_name='activitejour',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_jour', to='Appli.ville'),
        ),
        migrations.CreateModel(
            name='ActiviteComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('jour_numero', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_activites_complet/')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Appli.packcomplet')),
                ('villes', models.ManyToManyField(blank=True, related_name='activites_complet', to='Appli.ville')),
            ],
        ),
    ]
