# Generated by Django 5.2.6 on 2025-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='prix_moyen_dirham',
            field=models.FloatField(default=0.0, help_text='Coût moyen estimé par personne (à titre indicatif).'),
        ),
    ]
