# Generated by Django 5.2.6 on 2025-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packjour',
            old_name='prix',
            new_name='prix_eur',
        ),
        migrations.AddField(
            model_name='packjour',
            name='prix_mad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='packjour',
            name='prix_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='packcomplet',
            name='prix_eur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='packcomplet',
            name='prix_mad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='packcomplet',
            name='prix_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
