# Generated by Django 5.2.6 on 2025-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0002_rename_prix_packjour_prix_eur_packjour_prix_mad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionreservation',
            old_name='prix',
            new_name='prix_eur',
        ),
        migrations.AddField(
            model_name='optionreservation',
            name='prix_mad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='optionreservation',
            name='prix_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
