# Generated by Django 5.2.6 on 2025-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0003_remove_pack_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='prix_option_restaurant_dirham',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pack',
            name='prix_option_restaurant_dollar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pack',
            name='prix_option_restaurant_euros',
            field=models.FloatField(default=0.0, help_text="Coût ADDITIONNEL par personne pour l'option Restaurant (EUR)."),
        ),
        migrations.AlterField(
            model_name='pack',
            name='prix_option_ryad_dirham',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pack',
            name='prix_option_ryad_dollar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pack',
            name='type_pack',
            field=models.CharField(choices=[('AVENTURE', 'Aventure & Exploration'), ('LUXE', 'Séjour Luxe & Exclusif'), ('IMMERSION', 'Immersion Culturelle & Tradition'), ('DETENTE', 'Détente & Bien-être'), ('SUR_MESURE', 'Pack Sur Mesure (Générique)')], default='IMMERSION', help_text="Catégorisation du type d'expérience offerte.", max_length=50),
        ),
        migrations.AlterField(
            model_name='pack',
            name='type_restaurant',
            field=models.CharField(choices=[('GASTRONOMIQUE', 'Gastronomique / Haute Cuisine'), ('TRADITIONNEL', 'Cuisine Marocaine Traditionnelle'), ('FUSION', 'Fusion / Moderne'), ('VEGETARIEN', 'Végétarien / Santé')], default='TRADITIONNEL', help_text='Type de cuisine/établissement proposé en option Restaurant.', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservationpack',
            name='option_restaurant',
            field=models.BooleanField(default=False, help_text="Le client a-t-il choisi l'option Restaurant ?"),
        ),
    ]
