# Generated by Django 5.2.6 on 2025-10-31 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0004_alter_pack_prix_option_restaurant_dirham_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='activites',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pack',
        ),
        migrations.CreateModel(
            name='PackComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('resume_inspirant', models.TextField(blank=True, max_length=500, null=True)),
                ('type_pack', models.CharField(choices=[('AVENTURE', 'Aventure & Exploration'), ('LUXE', 'Séjour Luxe & Exclusif'), ('IMMERSION', 'Immersion Culturelle & Tradition'), ('DETENTE', 'Détente & Bien-être'), ('SUR_MESURE', 'Pack Sur Mesure (Générique)')], default='IMMERSION', max_length=50)),
                ('prix_par_personne_euros', models.FloatField(default=0.0, help_text='Prix de BASE par personne (EUR).')),
                ('prix_option_ryad_euros', models.FloatField(default=0.0, help_text="Coût ADDITIONNEL par personne pour l'option Ryad (Hébergement - EUR).")),
                ('prix_option_ryad_dirham', models.FloatField(default=0.0)),
                ('prix_option_ryad_dollar', models.FloatField(default=0.0)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('duree_standard_jours', models.PositiveSmallIntegerField(choices=[(3, '3 jours'), (5, '5 jours'), (8, '8 jours'), (10, '10 jours')], default=3, help_text='Durée du pack : 3, 5, 8 ou 10 jours.')),
                ('type_restaurant', models.CharField(choices=[('GASTRONOMIQUE', 'Gastronomique / Haute Cuisine'), ('TRADITIONNEL', 'Cuisine Marocaine Traditionnelle'), ('FUSION', 'Fusion / Moderne'), ('VEGETARIEN', 'Végétarien / Santé')], default='TRADITIONNEL', help_text='Type de cuisine/établissement proposé en option Restaurant.', max_length=50)),
                ('prix_option_restaurant_euros', models.FloatField(default=0.0, help_text="Coût ADDITIONNEL par personne pour l'option Restaurant (EUR).")),
                ('prix_option_restaurant_dirham', models.FloatField(default=0.0)),
                ('prix_option_restaurant_dollar', models.FloatField(default=0.0)),
                ('activites', models.ManyToManyField(help_text='Activités disponibles dans ce pack.', related_name='%(class)s_activites', to='Appli.activite')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_packs', to='Appli.ville')),
            ],
            options={
                'verbose_name': 'Pack Complet',
                'verbose_name_plural': 'Packs Complets',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='pack_complet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_complet', to='Appli.packcomplet'),
        ),
        migrations.AlterField(
            model_name='descriptionjournaliere',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='Appli.packcomplet'),
        ),
        migrations.CreateModel(
            name='PackJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('resume_inspirant', models.TextField(blank=True, max_length=500, null=True)),
                ('type_pack', models.CharField(choices=[('AVENTURE', 'Aventure & Exploration'), ('LUXE', 'Séjour Luxe & Exclusif'), ('IMMERSION', 'Immersion Culturelle & Tradition'), ('DETENTE', 'Détente & Bien-être'), ('SUR_MESURE', 'Pack Sur Mesure (Générique)')], default='IMMERSION', max_length=50)),
                ('prix_par_personne_euros', models.FloatField(default=0.0, help_text='Prix de BASE par personne (EUR).')),
                ('prix_option_ryad_euros', models.FloatField(default=0.0, help_text="Coût ADDITIONNEL par personne pour l'option Ryad (Hébergement - EUR).")),
                ('prix_option_ryad_dirham', models.FloatField(default=0.0)),
                ('prix_option_ryad_dollar', models.FloatField(default=0.0)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('activites', models.ManyToManyField(help_text='Activités disponibles dans ce pack.', related_name='%(class)s_activites', to='Appli.activite')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_packs', to='Appli.ville')),
            ],
            options={
                'verbose_name': 'Pack 1 Jour',
                'verbose_name_plural': 'Packs 1 Jour',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='pack_jour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Appli.packjour'),
        ),
        migrations.CreateModel(
            name='ReservationPackComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('demande', 'Demande effectuée'), ('en cours', 'En cours de traitement'), ('annulé', 'Demande Annulée'), ('traitée', 'Demande traitée'), ('validée', 'Transaction effectuée')], default='demande', max_length=60)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('nb_personne', models.SmallIntegerField()),
                ('montant_total', models.FloatField(default=0.0)),
                ('devise_paiement', models.CharField(blank=True, choices=[('EUR', '€ (Euros)'), ('MAD', 'DH (Dirhams Marocains)'), ('DOLLAR', '$ (Dollars)')], max_length=20, null=True)),
                ('lien_de_paiement', models.URLField(blank=True, max_length=300, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('option_restaurant', models.BooleanField(default=False)),
                ('option_ryad', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appli.packcomplet')),
                ('traiter_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_traites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation Pack Complet',
                'verbose_name_plural': 'Réservations Packs Complets',
            },
        ),
        migrations.CreateModel(
            name='ReservationPackJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('demande', 'Demande effectuée'), ('en cours', 'En cours de traitement'), ('annulé', 'Demande Annulée'), ('traitée', 'Demande traitée'), ('validée', 'Transaction effectuée')], default='demande', max_length=60)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('nb_personne', models.SmallIntegerField()),
                ('montant_total', models.FloatField(default=0.0)),
                ('devise_paiement', models.CharField(blank=True, choices=[('EUR', '€ (Euros)'), ('MAD', 'DH (Dirhams Marocains)'), ('DOLLAR', '$ (Dollars)')], max_length=20, null=True)),
                ('lien_de_paiement', models.URLField(blank=True, max_length=300, null=True)),
                ('date_debut', models.DateField(blank=True, help_text="Jour de l'activité.", null=True)),
                ('option_ryad', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Appli.packjour')),
                ('traiter_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_traites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation Pack 1 Jour',
                'verbose_name_plural': 'Réservations Packs 1 Jour',
            },
        ),
        migrations.DeleteModel(
            name='ReservationPack',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
