# Generated by Django 5.2.6 on 2025-11-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0005_remove_pack_activites_remove_pack_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packcomplet',
            name='prix_option_restaurant_euros',
            field=models.FloatField(default=0.0, help_text="Coût additionnel par personne pour l'option Restaurant (EUR)."),
        ),
        migrations.AlterField(
            model_name='packcomplet',
            name='prix_option_ryad_euros',
            field=models.FloatField(default=0.0, help_text="Coût additionnel par personne pour l'option Ryad (EUR)."),
        ),
        migrations.AlterField(
            model_name='packjour',
            name='prix_option_ryad_euros',
            field=models.FloatField(default=0.0, help_text="Coût additionnel par personne pour l'option Ryad (EUR)."),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demande effectuée'), ('en cours', 'En cours de traitement'), ('annulé', 'Demande annulée'), ('traitée', 'Demande traitée'), ('validée', 'Transaction effectuée')], default='demande', max_length=60),
        ),
        migrations.AlterField(
            model_name='reservationpackjour',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demande effectuée'), ('en cours', 'En cours de traitement'), ('annulé', 'Demande annulée'), ('traitée', 'Demande traitée'), ('validée', 'Transaction effectuée')], default='demande', max_length=60),
        ),
    ]
