# Generated by Django 5.2.6 on 2025-11-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0006_alter_packcomplet_prix_option_restaurant_euros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='type_activite',
            field=models.CharField(choices=[('activite_normal', 'Activité Basique'), ('excursion', 'Excursion')], default='activite_normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='activite',
            name='duree_texte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activite',
            name='nom_activite',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activite',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='Appli.ville'),
        ),
        migrations.AlterField(
            model_name='descriptionjournaliere',
            name='description',
            field=models.TextField(blank=True, default='Pas de description', null=True),
        ),
    ]
