# Generated by Django 5.2.6 on 2025-11-02 14:10

import Appli.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appli', '0007_activite_type_activite_alter_activite_duree_texte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='activite',
        ),
        migrations.AlterUniqueTogether(
            name='descriptionjournaliere',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='descriptionjournaliere',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pack_complet',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pack_jour',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ville',
        ),
        migrations.AlterModelOptions(
            name='packcomplet',
            options={'ordering': ['nom_pack'], 'verbose_name': 'Pack Complet', 'verbose_name_plural': 'Packs Complets'},
        ),
        migrations.AlterModelOptions(
            name='packjour',
            options={'ordering': ['nom_pack'], 'verbose_name': 'Pack 1 Jour', 'verbose_name_plural': 'Packs 1 Jour'},
        ),
        migrations.AlterModelOptions(
            name='reservationpackcomplet',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Réservation Pack Complet', 'verbose_name_plural': 'Réservations Pack Complet'},
        ),
        migrations.AlterModelOptions(
            name='reservationpackjour',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Réservation Pack 1 Jour', 'verbose_name_plural': 'Réservations Pack 1 Jour'},
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='duree_standard_jours',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_option_restaurant_dirham',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_option_restaurant_dollar',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_option_restaurant_euros',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_option_ryad_dirham',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_option_ryad_dollar',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_option_ryad_euros',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='prix_par_personne_euros',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='resume_inspirant',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='type_pack',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='type_restaurant',
        ),
        migrations.RemoveField(
            model_name='packcomplet',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='prix_option_ryad_dirham',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='prix_option_ryad_dollar',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='prix_option_ryad_euros',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='prix_par_personne_euros',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='resume_inspirant',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='type_pack',
        ),
        migrations.RemoveField(
            model_name='packjour',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='reservationpackcomplet',
            name='date_demande',
        ),
        migrations.RemoveField(
            model_name='reservationpackcomplet',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='reservationpackcomplet',
            name='lien_de_paiement',
        ),
        migrations.RemoveField(
            model_name='reservationpackcomplet',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='reservationpackcomplet',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='reservationpackcomplet',
            name='traiter_par',
        ),
        migrations.RemoveField(
            model_name='reservationpackjour',
            name='date_demande',
        ),
        migrations.RemoveField(
            model_name='reservationpackjour',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='reservationpackjour',
            name='lien_de_paiement',
        ),
        migrations.RemoveField(
            model_name='reservationpackjour',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='reservationpackjour',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='reservationpackjour',
            name='traiter_par',
        ),
        migrations.AddField(
            model_name='packcomplet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packcomplet',
            name='image_pack',
            field=models.ImageField(blank=True, null=True, upload_to='img_packs_complets/'),
        ),
        migrations.AddField(
            model_name='packcomplet',
            name='nom_pack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packcomplet',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='packjour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packjour',
            name='image_pack',
            field=models.ImageField(blank=True, null=True, upload_to='img_packs_jour/'),
        ),
        migrations.AddField(
            model_name='packjour',
            name='nom_pack',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packjour',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationpackcomplet',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservationpackjour',
            name='date_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='date_debut',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='date_fin',
            field=models.DateField(default=Appli.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='devise_paiement',
            field=models.CharField(choices=[('EUR', '€ (Euros)'), ('MAD', 'DH (Dirhams Marocains)'), ('DOLLAR', '$ (Dollars)')], default='MAD', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='nb_personne',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.packcomplet'),
        ),
        migrations.AlterField(
            model_name='reservationpackcomplet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_pack_complet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationpackjour',
            name='date_debut',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservationpackjour',
            name='devise_paiement',
            field=models.CharField(choices=[('EUR', '€ (Euros)'), ('MAD', 'DH (Dirhams Marocains)'), ('DOLLAR', '$ (Dollars)')], default='MAD', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservationpackjour',
            name='nb_personne',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservationpackjour',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appli.packjour'),
        ),
        migrations.AlterField(
            model_name='reservationpackjour',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_pack_jour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActiviteComplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_estimee_heures', models.PositiveIntegerField(default=4)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='img_activites_complets/')),
                ('villes', models.ManyToManyField(blank=True, related_name='activites_complets', to='Appli.ville')),
            ],
            options={
                'verbose_name': 'Activité Pack Complet',
                'verbose_name_plural': 'Activités Pack Complet',
                'ordering': ['nom_activite'],
            },
        ),
        migrations.AlterField(
            model_name='packcomplet',
            name='activites',
            field=models.ManyToManyField(blank=True, related_name='packs_complets', to='Appli.activitecomplet'),
        ),
        migrations.CreateModel(
            name='ActiviteJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_texte', models.CharField(blank=True, max_length=100, null=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='img_activites_jour/')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_jour', to='Appli.ville')),
            ],
            options={
                'verbose_name': 'Activité 1 Jour',
                'verbose_name_plural': 'Activités 1 Jour',
                'ordering': ['ville', 'nom_activite'],
            },
        ),
        migrations.AlterField(
            model_name='packjour',
            name='activites',
            field=models.ManyToManyField(blank=True, related_name='packs_jour', to='Appli.activitejour'),
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='DescriptionJournaliere',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
